### ISSUE TITLE
Error in installing the project with Go 1.18 - discussion

### ISSUE THREAD

**Issue by ahmadateya** [project-flotta/flotta-operator#162]
I am new to the Flotta project and the whole open source community, if there is something I am missing please correct me.

## The Problem

when trying to install the project on a machine with Go 1.18 it gives me an error of bin/controller-gen: No such file or directory 

running `make install` gives the following
> go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
go: added github.com/fatih/color v1.7.0
go: added github.com/gobuffalo/flect v0.2.0
go: added github.com/gogo/protobuf v1.3.1
go: added github.com/google/gofuzz v1.1.0
go: added github.com/inconshreveable/mousetrap v1.0.0
go: added github.com/json-iterator/go v1.1.8
go: added github.com/mattn/go-colorable v0.1.2
go: added github.com/mattn/go-isatty v0.0.8
go: added github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: added github.com/modern-go/reflect2 v1.0.1
go: added github.com/spf13/cobra v1.0.0
go: added github.com/spf13/pflag v1.0.5
go: added golang.org/x/mod v0.2.0
go: added golang.org/x/net v0.0.0-20200226121028-0de0cce0169b
go: added golang.org/x/sys v0.0.0-20191022100944-742c48ecaeb7
go: added golang.org/x/text v0.3.2
go: added golang.org/x/tools v0.0.0-20200616195046-dc31b401abb5
go: added golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: added gopkg.in/inf.v0 v0.9.1
go: added gopkg.in/yaml.v2 v2.2.8
go: added gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966
go: added k8s.io/api v0.18.2
go: added k8s.io/apiextensions-apiserver v0.18.2
go: added k8s.io/apimachinery v0.18.2
go: added k8s.io/klog v1.0.0
go: added k8s.io/utils v0.0.0-20200324210504-a9aa75ae1b89
go: added sigs.k8s.io/controller-tools v0.4.1
go: added sigs.k8s.io/structured-merge-diff/v3 v3.0.0
go: added sigs.k8s.io/yaml v1.2.0
bash: line 1: /home/ateya/Desktop/flotta-operator/bin/controller-gen: No such file or directory
make: * [Makefile:63: manifests] Error 127

after some search, I found this [issue](https://github.com/kubernetes-sigs/kubebuilder/issues/2543) in kubebuilder, they are not supporting Go 1.18 yet

## Notes:
- I tested it with the Go 1.17 and it works fine.
- I think the root cause for this issue is the deprecation of `go get` command in Go 1.18

### 1. update the docs and wait until kubebuilder finishes their update to get better results

I think we can wait until they finish their work in supporting Go 1.18 (and I can see they are actively working on this, due to the open issues and PRs they have related to this) and then update our project based on what they will do. and in the meantime, we can update our docs [here](https://github.com/project-flotta/flotta-operator/blob/main/README.md) and [here](https://github.com/project-flotta/flotta.github.io/blob/main/_posts/2022-03-02-getting-started-project-flotta.markdown) in the Prerequisites section that the project is supporting Go 1.18 yet, this could be a good first issue and I can work on this

### 2. fixing it ourselves
I tried to replace the command with go install [here](https://github.com/project-flotta/flotta-operator/blob/43205a5e4cbf5c90fcd3241e23d4c0a943f509a2/Makefile#L209) but it didn't work, gave me this error when running `make install`

> go: creating new go.mod: module tmp
Downloading sigs.k8s.io/kustomize/kustomize/v3@v3.8.7
go: sigs.k8s.io/kustomize/kustomize/v3@v3.8.7 (in sigs.k8s.io/kustomize/kustomize/v3@v3.8.7):
	The go.mod file for the module providing named packages contains one or
	more exclude directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
make: * [Makefile:192: kustomize] Error 1

**Comment by masayag** [comment]
Hi @ahmadateya! Thanks for looking into it.
I created an issue https://github.com/project-flotta/flotta-operator/issues/153 to upgrade few of used libraries which requires an upgrade to golang 1.17 as well.
This can be a good start towards moving to 1.18 and replacing the deprecated methods (`go get` with `go install`) as part of it.

Updating the docs is a good idea. Looking forward for the PR :-)

**Comment by ahmadateya** [comment]
Hi @masayag, Sorry for the late response I made this small PR #171 to fix this issue, it is just a tiny edit in the README.md file and I am willing to work on the upgrade issue #153
