### ISSUE TITLE
manager manifest in OCP flotta operator release v.0.0.1 points to the wrong image

### ISSUE THREAD

**Issue by jordigilh** [project-flotta/flotta-operator#206]
The image value in release 0.0.1 of the flotta operator for OCP points to the wrong image value:
`image: controller:latest`
The correct value should be:
`image: quay.io/project-flotta/flotta-operator` as it is shown in the K8s manifest.

**Comment by masayag** [comment]
Flotta operator v0.1.0 was released last week and should be considered the first supported release.
The prior draft release was removed.
