### ISSUE TITLE
For OpenShift, the OpenShift kube-rbac-proxy image must be used

### ISSUE THREAD

**Issue by vadimeisenbergibm** [project-flotta/flotta-operator#24]
See https://github.com/operator-framework/operator-sdk/issues/4684

I experience the error:

` Error: container create failed: time="2021-10-13T02:11:50Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"`

**Comment by pkliczewski** [comment]
@vadimeisenbergibm Thank you for reporting.

**Comment by pkliczewski** [comment]
@jakub-dzon please take a look

**Comment by masayag** [comment]
With v0.1.0 released, the image for OCP is `registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.9.0` and for k8s is `gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0`
